CLASS zcl_crp_messag_logger_enum DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
   CONSTANTS info TYPE I VALUE 1.
   CONSTANTS warning TYPE I VALUE 2.
   CONSTANTS error TYPE I VALUE 3.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_crp_messag_logger_enum IMPLEMENTATION.
ENDCLASS.
